name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SDL2
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev
      - name: Build
        run: make copy-release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: raytracer
          path: releases/raytracer.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/raytracer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
