on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Git tag to release (e.g. v1.0.0)'
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install SDL2 and MinGW
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev mingw-w64
      - name: Build
        run: make CXX=x86_64-w64-mingw32-g++ SDL_CONFIG=x86_64-w64-mingw32-sdl2-config copy-release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: raytracer
          path: releases/raytracer.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
          files: releases/raytracer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
